resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest

resources:
  - name: source
    type: git
    source:
      uri: ((github-uri))
      check_every: 5s
      branch: ((github-branch))
      private_key: ((github-key))
  - name: slack
    type: slack-notification
    source:
      url: ((slack-hook))

jobs:
  - name: run-tests
    plan:
      - get: source
        trigger: true
      - aggregate:
        - task: run lint rules
          file: source/ci/tasks/run_lint.yml
          params:
            REPO: ((github-repo))
          on_failure:
            put: slack
            params:
              text: ((build-link))
              attachments_file: messages/slack.txt
        - task: run unit tests
          file: source/ci/tasks/run_tests.yml
          params:
            REPO: ((github-repo))
          on_failure:
            put: slack
            params:
              text: ((build-link))
              attachments_file: messages/slack.txt

  - name: stage-deploy
    plan:
      - get: source
        trigger: true
        passed: [run-tests]
      - task: run build
        file: source/ci/tasks/run_build.yml
        params:
          APP_NAME: ((app-name))
          APP_URL_ACCOUNTS: ((stage-app-url-accounts))
          APP_URL_ANALYTICS: ((stage-app-url-analytics))
          APP_URL_AUDIENCES: ((stage-app-url-audiences))
          APP_URL_VIZIA: ((stage-app-url-vizia))
          AUTH_AUDIENCE: ((stage-auth-audience))
          AUTH_DOMAIN: ((stage-auth-domain))
          BW_DOMAIN: ((stage-bw-domain))
          MIXPANEL_TOKEN: ((stage-mixpanel-token))
          NODE_ENV: 'production'
          REPO: ((github-repo))
      - task: deploy to stage
        file: source/ci/tasks/run_deploy.yml
        params:
          APP_NAME: ((app-name))
          BRANCH: ((github-branch))
          GCP_SERVICE_ACCOUNT_KEY: ((stage-gcs-token))
          STORAGE_BUCKET: ((stage-bucket))

  - name: stage-automate
    plan:
      - get: source
        trigger: true
        passed: [stage-deploy]
      - task: run automation on stage
        file: source/ci/tasks/run_automation.yml
        params:
          AT_BASE_URL: ((stage-url))
          AT_IGNORE_CERT_ERRORS: false
          AT_LOGIN_PASSWORD: ((stage-at-login-password))
          AT_LOGIN_USERNAME: ((stage-at-login-username))
          AT_RUN_IN_BACKGROUND: true
          AUTH_AUDIENCE: ((stage-auth-audience))
          AUTH_DOMAIN: ((stage-auth-domain))
          REPO: ((github-uri))
          STORAGE_BUCKET: ((stage-bucket))
    on_failure:
      put: slack
      params:
        text: ((build-link))
        attachments_file: messages/slack.txt

  - name: prod-deploy
    plan:
      - get: source
        trigger: true
        passed: [stage-automate]
      - task: run build
        file: source/ci/tasks/run_build.yml
        params:
          APP_NAME: ((app-name))
          APP_URL_ACCOUNTS: ((prod-app-url-accounts))
          APP_URL_ANALYTICS: ((prod-app-url-analytics))
          APP_URL_AUDIENCES: ((prod-app-url-audiences))
          APP_URL_VIZIA: ((prod-app-url-vizia))
          AUTH_AUDIENCE: ((prod-auth-audience))
          AUTH_DOMAIN: ((prod-auth-domain))
          BW_DOMAIN: ((prod-bw-domain))
          MIXPANEL_TOKEN: ((prod-mixpanel-token))
          NODE_ENV: 'production'
          REPO: ((github-uri))
      - task: deploy to prod
        file: source/ci/tasks/run_deploy.yml
        params:
          APP_NAME: ((app-name))
          BRANCH: ((github-branch))
          GCP_SERVICE_ACCOUNT_KEY: ((prod-gcs-token))
          STORAGE_BUCKET: ((prod-bucket))

  - name: prod-automate
    plan:
      - get: source
        trigger: true
        passed: [prod-deploy]
      - task: run automation on prod
        file: source/ci/tasks/run_automation.yml
        params:
          AT_BASE_URL: ((prod-url))
          AT_IGNORE_CERT_ERRORS: false,
          AT_LOGIN_PASSWORD: ((prod-at-login-password))
          AT_LOGIN_USERNAME: ((prod-at-login-username))
          AT_RUN_IN_BACKGROUND: true
          AUTH_AUDIENCE: ((prod-auth-audience))
          AUTH_DOMAIN: ((prod-auth-domain))
          REPO: ((github-uri))
          STORAGE_BUCKET: ((prod-bucket))
    on_failure:
      put: slack
      params:
        text: ((build-link))
        attachments_file: messages/slack.txt
    on_success:
      put: slack
      params:
        text: ((build-link))
        attachments_file: messages/slack.txt
