---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: 8.5.0

inputs:
  - name: source

outputs:
  - name: build
  - name: messages

run:
  path: source/ci/scripts/run_build.sh
