---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: thatguynamedandy/node-xvfb
    tag: latest

inputs:
  - name: source

outputs:
  - name: messages

run:
  path: source/ci/scripts/run_automation.sh
